Change lat long data type to decimal + add lat long to anchors
skrgloliatgue/PetaNetra-Map-Editor pull request #60
Opened 2022-04-14 18:01 UTC by yafonia

2022-04-15 16:41 UTC, alifmahardhika commented on PetaNetra Map Editor/Utilities/GlobalVariables.swift
> +func joinLatLong(lat: Decimal, long: Decimal) -> String {
this function results in 3 decimal point string representation.
eg:
lat = 101.12345678
long = 90.12345678

result = 101.123,90.123.

used in arworldmap naming. i think should use 5 dec point minimal or just concat the lat,long without changes to decimal point

2022-04-15 16:42 UTC, alifmahardhika commented on PetaNetra Map Editor/Utilities/Networking/NetworkingUtils.swift
> +    func shortenCoordinateReturnString(coord: Decimal) -> String {
3 point decimal too

2022-04-15 16:42 UTC, alifmahardhika commented on PetaNetra Map Editor/Utilities/Networking/NetworkingUtils.swift
> +    func shortenCoordinate(coord: Decimal) -> Decimal {
same

2022-04-15 16:42 UTC, alifmahardhika commented on PetaNetra Map Editor/Services/Networking/UploadServices.swift
> +    func shortenCoordinateReturnString(coord: Decimal) -> String {
same

2022-04-15 16:43 UTC, alifmahardhika requested changes
update 3 point decimal uses to minimal 5 point atau gausa dipotong juga ndapapa

2022-04-16 15:26 UTC, yafonia commented
changed from 3 to 5 dec point. thanks alif!

2022-04-17 15:43 UTC, alifmahardhika approved these changes

2022-04-17 15:45 UTC, merged